from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
      path('', page_404, name='404'),
      path('dashboard/', dashboard_view, name='dashboard'),
      path("information/", information_view, name="information"),
      path("category/", category_view, name="category"),
      path("sub-category/", subcategory_view, name="sub-category"),
      path("region/", region_view, name="region"),
      path("about/", about_view, name="about"),
      path("profile/<int:pk>/", profile, name="profile"),
      path("all-admin/", all_admin, name="admin"),
      path('search/', search, name='search'),
      path("advertiser/", advertiser_view, name="advertiser"),
      path('in-admin-ads/', in_admin, name='in-admin'),
      path('accepted-ads/', accepted, name='accepted'),
      path('rejected-ads/', rejected, name='rejected'),
      path('sold-ads/', sold, name='sold'),
      path('accept-ads/<int:pk>/', accept, name='accept'),
      path('accept-ads-in/<int:pk>/', accept_in, name='accept-in'),
      path('reject-ads/<int:pk>/', reject, name='reject'),
      path('reject-ads-in/<int:pk>/', reject_in, name='reject-in'),
      path('sale-ads/<int:pk>/', sale, name='sale'),
      path('sign-up/', sign_up, name='sign-up'),
      path('single-user/<int:pk>/', single_user, name='single'),
      path('single-ads/<int:pk>/', single_ads, name='single-ads'),
      path('login', for_login, name='login'),
      path('logout/', logout_view, name='logout'),
      path('reset-password/', reset, name='reset'),
      path('sign-in/', sign_in, name='sign-in'),
      path("add-info/", add_info, name="add-info"),
      path("add-about/", add_about, name="add-about"),
      path("add-category/", add_category, name="add-category"),
      path("add-region/", add_region, name="add-region"),
      path("add-sub/", add_sub, name="add-sub_cat"),
      path('delete-category/<int:pk>/', delete_category, name='delete-category'),
      path('delete-sub-cat/<int:pk>/', delete_sub, name='delete-sub-cat'),
      path('delete-info/<int:pk>/', delete_info, name='delete-info'),
      path('delete-region/<int:pk>/', delete_region, name='delete-region'),
      path('delete-about/<int:pk>/', delete_about, name='delete-about'),
      path('update-category/<int:pk>/', update_category, name='update-category'),
      path('update-about/<int:pk>/', update_about, name='update-about'),
      path('update-sub-cat/<int:pk>/', update_sub, name='update-sub'),
      path('update-info/<int:pk>/', up_info, name='update-info'),
      path('update-region/<int:pk>/', update_region, name='update-region'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
